name = "lapce-yaml"
display-name = "YAML"
description = "YAML for Lapce: powered by yaml-language-server"
version = "0.0.1"
author = "panekj"
repository = "panekj/lapce-yaml"
wasm = "bin/lapce-yaml.wasm"

[activation]
language = ["yaml"]
workspace-contains = ["*/*.yml", "*/*.yaml"]

[configuration.yaml.yamlVersion]
default = "1.2"
description = "Set default YAML spec version (1.2 or 1.1)"

[configuration.yaml.format.enable]
default = true
description = "Enable/disable default YAML formatter (requires restart)"

[configuration.yaml.format.singleQuote]
default = false
description = "Use single quotes instead of double quotes"

[configuration.yaml.format.bracketSpacing]
default = true
description = "Print spaces between brackets in objects"

[configuration.yaml.format.proseWrap]
default = "preserve"
description = "Always: wrap prose if it exceeds the print width, Never: never wrap the prose, Preserve: wrap prose as-is"

[configuration.yaml.format.printWidth]
default = 80
description = "Specify the line length that the printer will wrap on"

[configuration.yaml.validate]
default = true
description = "Enable/disable validation feature"

[configuration.yaml.hover]
default = true
description = "Enable/disable hover"

[configuration.yaml.completion]
default = true
description = "Enable/disable autocompletion"

[configuration.yaml.schemas]
default = {}
description = "Helps you associate schemas with files in a glob pattern"

[configuration.yaml.schemaStore.enable]
default = true
description = "When set to true the YAML language server will pull in all available schemas from JSON Schema Store"

[configuration.yaml.schemaStore.url]
default = "https://www.schemastore.org/api/json/catalog.json"
description = "URL of a schema store catalog to use when downloading schemas."

[configuration.yaml.customTags]
default = []
description = 'Array of custom tags that the parser will validate against. It has two ways to be used. Either an item in the array is a custom tag such as "!Ref" and it will automatically map !Ref to scalar or you can specify the type of the object !Ref should be e.g. "!Ref sequence". The type of object can be either scalar (for strings and booleans), sequence (for arrays), map (for objects).'

[configuration.yaml.maxItemsComputed]
default = 5000
description = "The maximum number of outline symbols and folding regions computed (limited for performance reasons)."

[configuration.yaml.editor.tabSize]
description = "The number of spaces to use when autocompleting. Takes priority over editor.tabSize."

[configuration.yaml.editor.formatOnType]
description = "Enable/disable on type indent and auto formatting array"

[configuration.editor.tabSize]
default = 2
description = "The number of spaces to use when autocompleting. Default is 2."

[configuration.http.proxy]
description = "The URL of the proxy server that will be used when attempting to download a schema. If it is not set or it is undefined no proxy server will be used."

[configuration.http.proxyStrictSSL]
default = false
description = "If true the proxy server certificate should be verified against the list of supplied CAs. Default is false."

[configuration.yaml.disableDefaultProperties]
default = false
description = "Disable adding not required properties with default values into completion text"

[configuration.yaml.suggest.parentSkeletonSelectedFirst]
description = "If true, the user must select some parent skeleton first before autocompletion starts to suggest the rest of the properties.\nWhen yaml object is not empty, autocompletion ignores this setting and returns all properties and skeletons."

[configuration.yaml.style.flowMapping]
description = 'Forbids flow style mappings if set to "forbid"'

[configuration.yaml.style.flowSequence]
description = 'Forbids flow style sequences if set to "forbid"'
