name = "lapce-yaml"
display-name = "YAML"
description = "YAML for Lapce: powered by yaml-language-server"
version = "0.0.1"
author = "panekj"
repository = "panekj/lapce-yaml"
wasm = "bin/lapce-yaml.wasm"
